//filteredFields: ['isActive', 'missedDose']
// dataList - medication dataset/obj
//label map = { isActive: { true: 'Active', false: 'Inactive' } }
// creates filter options dynamically from your data
export function getDynamicFilterOptions(
	dataList,
	filteredFields,
	labelMap = {}
) {
	return filteredFields.flatMap((field) => {
		//getting all the unique values from the fields of the dataList
		// eg. Set {true}
		const uniqueVals = [...new Set(dataList.map((item) => item[field]))];

		//mapping the values based off the label map to get readable form using labelMap.
		return uniqueVals.map((value) => {
			const label =
				labelMap[field]?.[value] !== undefined
					? labelMap[field][value]
					: String(value);
			//returns filter options eg. { label: 'Active', field: 'isActive', value: true }
			return { label, field, value };
		});
	});
}

//dataList - full dataset
//filterOptions - generated by getDynamicFilterOptions [ { label: 'Active', field: 'isActive', value: true },]
//selectedLabels - the selected filter options ['Active', 'Missed']
//applies the filter to the dataList based on the selectedLabels
export function applyFilter(dataList, filterOptions, selectedLabels) {
	//if none of the filter options have been selected, return the whole datalist
	if (selectedLabels.length === 0) {
		return dataList;
	}

	//grouping selected filters by field
	// eg. isActive: Set {true}, missedDose: Set {false}
	const groupByField = {};

	// loop through all available filter options
	for (const option of filterOptions) {
		//if this option is selected by user
		if (selectedLabels.includes(option.label)) {
			// if this field doesn't exist yet, create a new set for it
			if (!groupByField[option.field]) {
				groupByField[option.field] = new Set();
			}
			//add the value to the set for this field
			groupByField[option.field].add(option.value);
		}
	}

	return dataList.filter((item) => {
		//filtering list making sure that items inside list fulfill both filters
		for (const field in groupByField) {
			if (!groupByField[field].has(item[field])) {
				return false;
			}
		}

		return true;
	});
}
