name: Deploy All Services

on:
  workflow_run:
    workflows: ['Build & Dockerize MediMind']
    types:
      - completed

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install community.docker

      - name: Write SSH key for App
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2APP_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy App with Ansible
        env:
          EC2APP_IP: ${{ secrets.EC2APP_IP }}
          EC2APP_USER: ${{ secrets.EC2APP_USER }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          CORS_ALLOWED_ORIGIN: ${{ secrets.CORS_ALLOWED_ORIGIN }}
          VITE_SERVER: ${{ secrets.VITE_SERVER }}
        run: |
          cd ansible
          ansible-playbook deploy.yml -i inventory.py

  verify-all:
    runs-on: ubuntu-latest
    needs: [deploy-app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install community.docker

      - name: Write App SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2APP_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Verify App Services
        env:
          EC2APP_IP: ${{ secrets.EC2APP_IP }}
          EC2APP_USER: ${{ secrets.EC2APP_USER }}
        run: |
          cd ansible
          ansible-playbook verify-app.yml -i inventory.py
