name: "Generate Final Report"

on:
  workflow_dispatch:
    inputs:
      lint_run_id:
        description: 'Workflow run ID for Lint'
        required: true
      sca_run_id:
        description: 'Workflow run ID for SCA'
        required: true
      sast_run_id:
        description: 'Workflow run ID for SAST'
        required: true

jobs:
  final-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Lint artifacts
        uses: actions/download-artifact@v4
        with:
          name: eslint-report
          path: frontend/eslint-report
          run-id: ${{ github.event.inputs.lint_run_id }}

      - name: Download SCA artifacts
        uses: actions/download-artifact@v4
        with:
          name: snyk-node-report
          path: artifacts/sca
          run-id: ${{ github.event.inputs.sca_run_id }}

      - name: Download SAST artifacts
        uses: actions/download-artifact@v4
        with:
          name: codeql-results
          path: artifacts/sast
          run-id: ${{ github.event.inputs.sast_run_id }}

      - name: Generate Final Report
        run: |
          mkdir -p artifacts/final
          report_file="artifacts/final/final-report.txt"
          echo "MediMind CI/CD Final Report - $(date)" > $report_file
          echo "" >> $report_file
          echo "=== Lint ===" >> $report_file
          ls artifacts/eslint-report || echo "No Lint artifact found" >> $report_file
          echo "" >> $report_file
          echo "=== SCA ===" >> $report_file
          ls artifacts/sca || echo "No SCA artifact found" >> $report_file
          echo "" >> $report_file
          echo "=== SAST ===" >> $report_file
          ls artifacts/sast || echo "No SAST artifact found" >> $report_file

      - name: Upload Final Report
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: artifacts/final/final-report.txt
