name: "Generate Final CI/CD Report"

on:
  workflow_run:
    workflows: 
      - "Linting CI & Build"
      - "SCA - Dependency Scan"
      - "SAST - Static Code Analysis & Build"
    types:
      - completed

jobs:
  final-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------
      # Download artifacts from previous workflows
      # ---------------------
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare Final Report Folder
        run: mkdir -p artifacts/final

      - name: Generate Final Report
        run: |
          report_file="artifacts/final/final-report.txt"
          echo "======================" > $report_file
          echo "MediMind CI/CD Final Report - $(date)" >> $report_file
          echo "======================" >> $report_file
          echo "" >> $report_file

          echo "=== Linting Summary ===" >> $report_file
          if [ -f artifacts/eslint-report/eslint-report.txt ]; then
            echo "- Frontend Lint Issues:" >> $report_file
            grep -c "error" artifacts/eslint-report/eslint-report.txt || echo "0 errors" >> $report_file
          fi

          if [ -f artifacts/pylint-report/pylint-report.txt ]; then
            echo "- Python Lint Issues:" >> $report_file
            grep -c "error" artifacts/pylint-report/pylint-report.txt || echo "0 errors" >> $report_file
          fi

          echo "" >> $report_file
          echo "=== SCA (Dependency Scan) Summary ===" >> $report_file
          if [ -f artifacts/snyk-java-report/snyk-java-report.json ]; then
            vulns=$(jq '.vulnerabilities | length' artifacts/snyk-java-report/snyk-java-report.json)
            echo "- Backend Vulnerabilities: $vulns" >> $report_file
          fi
          if [ -f artifacts/snyk-node-report/snyk-node-report.json ]; then
            vulns=$(jq '.vulnerabilities | length' artifacts/snyk-node-report/snyk-node-report.json)
            echo "- Frontend Vulnerabilities: $vulns" >> $report_file
          fi

          echo "" >> $report_file
          echo "=== SAST (CodeQL) Summary ===" >> $report_file
          echo "See Security tab for full CodeQL results." >> $report_file

          echo "" >> $report_file
          echo "=== Unit Test Summary ===" >> $report_file
          if ls backend/target/surefire-reports/*.xml 1> /dev/null 2>&1; then
            total=$(grep "<testsuite" backend/target/surefire-reports/*.xml | wc -l)
            failures=$(grep "<failure" backend/target/surefire-reports/*.xml | wc -l)
            echo "Total test suites: $total, Failures: $failures" >> $report_file
          else
            echo "No unit test results found." >> $report_file
          fi

      - name: Upload Final Report
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: artifacts/final/final-report.txt
