name: "Generate Demo Final Report"

on:
  workflow_dispatch:  # Manual trigger

jobs:
  final-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------
      # Download all artifacts from previous runs
      # ---------------------
      - name: Download Lint Artifacts
        uses: actions/download-artifact@v4
        with:
          name: eslint-report
          path: frontend/eslint-report
      - uses: actions/download-artifact@v4
        with:
          name: pylint-report
          path: artifacts/pylint-report
      - uses: actions/download-artifact@v4
        with:
          name: nbqa-notebook-report
          path: artifacts/nbqa-notebook-report

      # Optional: Download SCA reports if they exist
      - name: Download SCA Artifacts
        uses: actions/download-artifact@v4
        with:
          name: snyk-node-report
          path: artifacts/snyk-node-report
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
          name: snyk-java-report
          path: artifacts/snyk-java-report
        continue-on-error: true

      # ---------------------
      # Aggregate Final Report
      # ---------------------
      - name: Generate Final Report
        run: |
          mkdir -p artifacts/final
          report_file="artifacts/final/final-report.txt"
          
          echo "======================" > $report_file
          echo "MediMind CI/CD Final Report - $(date)" >> $report_file
          echo "======================" >> $report_file
          echo "" >> $report_file

          echo "=== Linting Summary ===" >> $report_file
          cat artifacts/eslint-report/eslint-report.txt >> $report_file
          echo "" >> $report_file
          cat artifacts/pylint-report/pylint-report.txt >> $report_file
          echo "" >> $report_file
          cat artifacts/nbqa-notebook-report/nbqa-notebook-report.txt >> $report_file
          echo "" >> $report_file

          echo "=== SCA (Dependency Scan) Summary ===" >> $report_file
          if [ -f artifacts/snyk-node-report/snyk-node-report.json ]; then
            echo "- Node vulnerabilities:" >> $report_file
            jq '.vulnerabilities | length' artifacts/snyk-node-report/snyk-node-report.json >> $report_file
          fi
          if [ -f artifacts/snyk-java-report/snyk-java-report.json ]; then
            echo "- Java vulnerabilities:" >> $report_file
            jq '.vulnerabilities | length' artifacts/snyk-java-report/snyk-java-report.json >> $report_file
          fi
          echo "" >> $report_file

          echo "=== SAST (CodeQL) Summary ===" >> $report_file
          echo "See Security tab for detailed CodeQL alerts." >> $report_file
          echo "" >> $report_file

      # ---------------------
      # Upload Final Report
      # ---------------------
      - name: Upload Final Report
        uses: actions/upload-artifact@v4
        with:
          name: final-demo-report
          path: artifacts/final/final-report.txt
