name: "Linting CI & Build"

on:
  push:
    branches:
      - main
      - frontend-*
      - backend-(java-springboot)
      - android-*
      - machine-learning
      
  pull_request:
    branches:
      - main
      - frontend-*
      - backend-(java-springboot)
      - android-*
      - machine-learning
      - demo/*

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------
      # Linting Steps
      # ---------------------
      - name: Lint React frontend
        working-directory: ./frontend
        run: |
          npm install
          if npm run | grep -q "lint"; then
            npm run lint > eslint-report.txt 2>&1 || true
          else
            echo "No lint script defined" > eslint-report.txt
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: frontend/eslint-report.txt

      - name: Lint Python ML
        working-directory: ./ml
        run: |
          pip install pylint nbqa
          pylint *.py > pylint-report.txt 2>&1 || true
          if ls *.ipynb 1> /dev/null 2>&1; then
            nbqa pylint *.ipynb > nbqa-notebook-report.txt 2>&1 || true
          else
            echo "No Jupyter notebooks found" > nbqa-notebook-report.txt
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: ml/pylint-report.txt
      - uses: actions/upload-artifact@v4
        with:
          name: nbqa-notebook-report
          path: ml/nbqa-notebook-report.txt

      - name: Android Lint
        working-directory: ./android
        run: ./gradlew lint
      - uses: actions/upload-artifact@v4
        with:
          name: android-lint-report
          path: android/app/build/reports/lint-results-*.html

      
