name: "Linting CI"

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact folder
        run: |
          mkdir -p artifacts/lint

      # React Lint
      - name: Lint React frontend
        working-directory: ./frontend
        run: |
          npm install
          if npm run | grep -q "lint"; then
            npm run lint > ../artifacts/lint/eslint-report.txt || echo "Lint failed" > ../artifacts/lint/eslint-report.txt
          else
            echo "No lint script defined" > ../artifacts/lint/eslint-report.txt
          fi
          

      - name: Upload ESLint Report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: artifacts/lint/eslint-report.txt

      # Python Lint
      - name: Lint Python ML
        working-directory: ./ml
        run: |
          pip install pylint
          pylint *.py > ../artifacts/lint/pylint-report.txt || true

      - name: Upload Pylint Report
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: artifacts/lint/pylint-report.txt
 
      # Jupyter Notebook nbqa
      - name: Lint Jupyter notebooks
        working-directory: ./ml
        run: |
          pip install nbqa pylint
          if ls *.ipynb 1> /dev/null 2>&1; then
            nbqa pylint *.ipynb > ../../artifacts/lint/nbqa-notebook-report.txt || echo "nbqa failed" > ../../artifacts/lint/nbqa-notebook-report.txt
          else
            echo "No Jupyter notebooks found" > ../../artifacts/lint/nbqa-notebook-report.txt
          fi

      - name: Upload Jupyter Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: nbqa-notebook-report
          path: artifacts/lint/nbqa-notebook-report.txt

           # Android Lint
      - name: Android Lint
        working-directory: ./android
        run: ./gradlew lint
      
      - name: Upload Android Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: android-lint-report
          path: android/app/build/reports/lint-results-*.html
