name: "Linting CI & Build"

on:
  push:
    branches:
      - main
      - frontend
      - backend
      - android
      - ml
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------
      # Linting Steps
      # ---------------------
      - name: Lint React frontend
        working-directory: ./frontend
        run: |
          npm install
          if npm run | grep -q "lint"; then
            npm run lint > eslint-report.txt 2>&1 || true
          else
            echo "No lint script defined" > eslint-report.txt
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: frontend/eslint-report.txt

      - name: Lint Python ML
        working-directory: ./ml
        run: |
          pip install pylint nbqa
          pylint *.py > pylint-report.txt 2>&1 || true
          if ls *.ipynb 1> /dev/null 2>&1; then
            nbqa pylint *.ipynb > nbqa-notebook-report.txt 2>&1 || true
          else
            echo "No Jupyter notebooks found" > nbqa-notebook-report.txt
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: ml/pylint-report.txt
      - uses: actions/upload-artifact@v4
        with:
          name: nbqa-notebook-report
          path: ml/nbqa-notebook-report.txt

      - name: Android Lint
        working-directory: ./android
        run: ./gradlew lint
      - uses: actions/upload-artifact@v4
        with:
          name: android-lint-report
          path: android/app/build/reports/lint-results-*.html

      # ---------------------
      # Automated Build
      # ---------------------
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot Backend
        working-directory: ./backend
        run: mvn clean package -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

      - name: Build React Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/

      - name: Build Android App (Debug APK)
        working-directory: ./android
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/*.apk
