name: "SAST - Static Code Analysis & Build"

on:
  push:
    branches:
      - main
      - frontend
      - backend
      - android
      - ml
  pull_request:
    branches:
      - main

jobs:
  codeql-sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # ---------------------
      # Automated Build
      # ---------------------
      - name: Build Spring Boot Backend
        working-directory: ./backend
        run: mvn clean package -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

      - name: Build React Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/

      - name: Build Android App (Debug APK)
        working-directory: ./android
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/*.apk

      # ---------------------
      # CodeQL Analysis
      # ---------------------
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java,javascript

      # --- Build Step for Java ---
      - name: Build Java for CodeQL
        working-directory: ./backend
        run: mvn clean compile -DskipTests
      
      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3
