name: 'SAST - Static Code Analysis & Build'

on:
  push:
    branches:
      - main
      - frontend-*
      - backend-(java-springboot)
      - android-*
      - machine-learning

  pull_request:
    branches:
      - main
      - frontend-*
      - backend-(java-springboot)
      - android-*
      - machine-learning
      - demo/*

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql-sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------
      # Set up Java 21 for backend build
      # ---------------------
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Verify Java setup
        run: |
          echo "Java version: $(java -version 2>&1)"
          echo "JAVA_HOME: $JAVA_HOME"
          echo "Maven version: $(mvn -version 2>&1)"

      # ---------------------
      # CodeQL Analysis
      # ---------------------
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java,javascript,python,kotlin
          config-file: ./.github/codeql/codeql-config.yml

      # Build for CodeQL Java Analysis
      - name: Build Java for CodeQL
        working-directory: ./backend
        run: |
          if [ -f "pom.xml" ]; then
            echo "Java version: $(java -version 2>&1 | head -n 1)"
            echo "Maven version: $(mvn -version 2>&1 | head -n 1)"
            echo "Current directory: $(pwd)"
            echo "Files in current directory:"
            ls -la
            echo "Attempting Maven build..."
            mvn clean compile -DskipTests || {
              echo "❌ Maven build failed"
              echo "Trying with verbose output..."
              mvn clean compile -DskipTests -X
              exit 1
            }
            echo "✅ Java build completed"
          else
            echo "⚠️  No pom.xml found in backend directory"
          fi
        continue-on-error: true

      # Build for CodeQL JavaScript Analysis
      - name: Build JavaScript for CodeQL
        working-directory: ./frontend
        run: |
          if [ -f "package.json" ]; then
            npm ci
            echo "✅ JavaScript build completed"
          else
            echo "⚠️  No package.json found in frontend directory"
          fi
        continue-on-error: true

      # Build for CodeQL Python Analysis
      - name: Build Python for CodeQL
        working-directory: ./ml
        run: |
          if [ -d "." ]; then
            python -m pip install --upgrade pip
            if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
              echo "✅ Python dependencies installed"
            else
              echo "⚠️  No requirements.txt found, installing basic packages"
              pip install pandas numpy scikit-learn
            fi
            echo "✅ Python build completed"
          else
            echo "⚠️  ML directory not found"
          fi
        continue-on-error: true

      # Build for CodeQL Kotlin/Android Analysis
      - name: Build Kotlin for CodeQL
        working-directory: ./android
        run: |
          if [ -f "build.gradle.kts" ] || [ -f "build.gradle" ]; then
            chmod +x ./gradlew
            ./gradlew clean
            ./gradlew compileDebugKotlin
            echo "✅ Kotlin build completed"
          else
            echo "⚠️  No build.gradle found in android directory"
          fi
        continue-on-error: true

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3

      # Generate SAST Report
      - name: Generate SAST Report
        run: |
          mkdir -p security-reports
          echo "# CodeQL SAST Analysis Report" > security-reports/codeql-sast-report.md
          echo "Generated: $(date)" >> security-reports/codeql-sast-report.md
          echo "" >> security-reports/codeql-sast-report.md
          echo "## Analysis Summary" >> security-reports/codeql-sast-report.md
          echo "- Java (Backend): Analyzed" >> security-reports/codeql-sast-report.md
          echo "- JavaScript (Frontend): Analyzed" >> security-reports/codeql-sast-report.md
          echo "- Python (ML): Analyzed" >> security-reports/codeql-sast-report.md
          echo "- Kotlin (Android): Analyzed" >> security-reports/codeql-sast-report.md
          echo "" >> security-reports/codeql-sast-report.md
          echo "## Security Alerts" >> security-reports/codeql-sast-report.md
          echo "Check GitHub Security tab for detailed CodeQL alerts." >> security-reports/codeql-sast-report.md
          echo "" >> security-reports/codeql-sast-report.md
          echo "## Secret Scanning" >> security-reports/codeql-sast-report.md
          echo "- CodeQL includes built-in secret scanning" >> security-reports/codeql-sast-report.md
          echo "- Detects API keys, passwords, tokens, and credentials" >> security-reports/codeql-sast-report.md
          echo "- All findings appear in GitHub Security tab" >> security-reports/codeql-sast-report.md

      - name: Upload SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sast-report
          path: security-reports/codeql-sast-report.md
