name: 'SAST - Static Code Analysis & Build'

on:
  push:
    branches:
      - main
      - frontend-*
      - backend-(java-springboot)
      - android-*
      - machine-learning

  pull_request:
    branches:
      - main
      - frontend-*
      - backend-(java-springboot)
      - android-*
      - machine-learning
      - demo/*

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql-sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------
      # Automated Build
      # ---------------------
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # --- Backend Build ---
      - name: Build Spring Boot Backend
        working-directory: ./backend
        run: mvn clean package -DskipTests
      - name: Debug Backend Output
        run: ls -R ./backend/target
      - uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

      # --- Frontend (React) Build ---
      - name: Build React Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
          ls -R  # debug
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/

      # --- Android Build (Debug APK) ---
      - name: Build Android App (Debug APK)
        working-directory: ./android
        run: ./gradlew assembleDebug
      - name: Debug Android Output
        run: ls -R ./android/app/build/outputs/apk/debug
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/*.apk

      # ---------------------
      # CodeQL Analysis
      # ---------------------
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java,javascript,python,kotlin
          config-file: ./.github/codeql/codeql-config.yml

      # Build for CodeQL Java Analysis
      - name: Build Java for CodeQL
        working-directory: ./backend
        run: mvn clean compile -DskipTests

      # Build for CodeQL JavaScript Analysis
      - name: Build JavaScript for CodeQL
        working-directory: ./frontend
        run: npm ci

      # Build for CodeQL Python Analysis
      - name: Build Python for CodeQL
        working-directory: ./ml
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      # Build for CodeQL Kotlin/Android Analysis
      - name: Build Kotlin for CodeQL
        working-directory: ./android
        run: |
          ./gradlew clean
          ./gradlew compileDebugKotlin

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3

      # Generate SAST Report
      - name: Generate SAST Report
        run: |
          mkdir -p security-reports
          echo "# CodeQL SAST Analysis Report" > security-reports/codeql-sast-report.md
          echo "Generated: $(date)" >> security-reports/codeql-sast-report.md
          echo "" >> security-reports/codeql-sast-report.md
          echo "## Analysis Summary" >> security-reports/codeql-sast-report.md
          echo "- Java (Backend): Analyzed" >> security-reports/codeql-sast-report.md
          echo "- JavaScript (Frontend): Analyzed" >> security-reports/codeql-sast-report.md
          echo "- Python (ML): Analyzed" >> security-reports/codeql-sast-report.md
          echo "- Kotlin (Android): Analyzed" >> security-reports/codeql-sast-report.md
          echo "" >> security-reports/codeql-sast-report.md
          echo "## Security Alerts" >> security-reports/codeql-sast-report.md
          echo "Check GitHub Security tab for detailed CodeQL alerts." >> security-reports/codeql-sast-report.md
          echo "" >> security-reports/codeql-sast-report.md
          echo "## Secret Scanning" >> security-reports/codeql-sast-report.md
          echo "- CodeQL includes built-in secret scanning" >> security-reports/codeql-sast-report.md
          echo "- Detects API keys, passwords, tokens, and credentials" >> security-reports/codeql-sast-report.md
          echo "- All findings appear in GitHub Security tab" >> security-reports/codeql-sast-report.md

      - name: Upload SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sast-report
          path: security-reports/codeql-sast-report.md
