name: "SAST - Static Code Analysis"

on:
  push:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql-sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java,javascript,python

      - name: Build Spring Boot for SAST
        working-directory: ./backend
        run: mvn clean compile -DskipTests

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3

      # Optional: Android Lint
      - name: Android Lint
        working-directory: ./android
        run: ./gradlew lint

