name: "SCA - Dependency Vulnerability Scan"

on:
  push:
    branches: [main]

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Snyk React
      - name: Snyk React Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=frontend/package.json

      # Snyk Java
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Snyk Spring Boot Scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=backend/pom.xml

      # Python pip-audit (open-source alternative)
      - name: Python Dependency Audit
        working-directory: ./ml
        run: |
          pip install pip-audit
          pip install -r requirements.txt
          pip-audit

