name: "SCA - Dependency Vulnerability Scan & Build"

on:
  push:
    branches:
      - main
      - frontend-(react)
      - backend-(java-springboot)
      - android
      - machine-learning
  pull_request:
    branches:
      - main

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # --- React (Node.js) ---
      - name: Install Node.js dependencies
        working-directory: ./frontend
        run: npm install
      - name: Snyk Scan (React)
        working-directory: ./frontend
        run: snyk test --file=package.json --json > snyk-node-report.json || echo '{}' > snyk-node-report.json
      - uses: actions/upload-artifact@v4
        with:
          name: snyk-node-report
          path: frontend/snyk-node-report.json

      # --- Java (Spring Boot) ---
      - name: Snyk Scan (Java Maven)
        working-directory: ./backend
        run: snyk test --file=pom.xml --json-file-output=snyk-java-report.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: snyk-java-report
          path: backend/snyk-java-report.json

      # --- Python (ML) ---
      - name: Install Python dependencies
        working-directory: ./ml
        run: |
          pip install -r requirements.txt
          pip install torch torchvision torchaudio pip-audit || true
      - name: Python Dependency Audit (pip-audit)
        working-directory: ./ml
        run: pip-audit -r requirements.txt -f json -o pip-audit-report.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: ml/pip-audit-report.json

    
