name: "SCA - Dependency Scan with Trivy"

on:
  push:
    branches:
      - main
      - frontend-(react)
      - backend-(java-springboot)
      - android
      - machine-learning
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv trivy /usr/local/bin/

      # 3️⃣ Create artifact folder
      - name: Prepare Artifacts Folder
        run: mkdir -p artifacts/sca

      # 4️⃣ Scan React Frontend (Node.js)
      - name: Scan React Frontend
        working-directory: ./frontend
        run: |
          npm install || true
          trivy fs --security-checks vuln --ignore-unfixed --exit-code 0 --format json -o ../../artifacts/sca/trivy-node-report.json .

      # 5️⃣ Scan Python ML Dependencies
      - name: Scan Python ML
        working-directory: ./ml
        run: |
          pip install -r requirements.txt || true
          trivy fs --security-checks vuln --ignore-unfixed --exit-code 0 --format json -o ../../artifacts/sca/trivy-python-report.json .

      # 6️⃣ Scan Java Backend Dependencies
      - name: Scan Java Backend
        working-directory: ./backend
        run: |
          mvn dependency:copy-dependencies || true
          trivy fs --security-checks vuln --ignore-unfixed --exit-code 0 --format json -o ../../artifacts/sca/trivy-java-report.json .

      # 7️⃣ Optional: Scan Docker Image for Backend
      - name: Scan Backend Docker Image
        run: |
          docker build -t medimind-backend:latest ./backend
          trivy image --security-checks vuln --ignore-unfixed --exit-code 0 --format json -o artifacts/sca/trivy-backend-docker.json medimind-backend:latest

      # 8️⃣ Upload reports as artifacts
      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: artifacts/sca/*.json
