name: "SCA - Dependency Scan (Trivy)"

on:
  push:
    branches:
      - main
      - frontend-(react)
      - backend-(java-springboot)
      - android
      - machine-learning
  pull_request:
    branches:
      - main

jobs:
  sca-trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------
      # Install Trivy
      # ---------------------
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/

      - name: Prepare Artifact Directory
        run: mkdir -p artifacts/sca

      # ---------------------
      # Backend (Java) Scan
      # ---------------------
      - name: Scan Backend (Java)
        working-directory: ./backend
        run: |
          trivy fs --security-checks vuln --format json --output ../artifacts/sca/backend-trivy.json .

      # ---------------------
      # Frontend (Node.js) Scan
      # ---------------------
      - name: Scan Frontend (Node.js)
        working-directory: ./frontend
        run: |
          npm install
          trivy fs --security-checks vuln --format json --output ../artifacts/sca/frontend-trivy.json .

      # ---------------------
      # ML (Python) Scan
      # ---------------------
      - name: Scan Python ML
        working-directory: ./ml
        run: |
          pip install -r requirements.txt || true
          trivy fs --security-checks vuln --format json --output ../artifacts/sca/ml-trivy.json .

     # ---------------------
      # Android Scan (APK)
      # ---------------------
      - name: Build Android APK
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Scan Android APK with Trivy
        run: |
          APK_PATH=$(find android/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          echo "Scanning APK: $APK_PATH"
          mkdir -p artifacts/sca
          trivy fs --scanners vuln --format json --output artifacts/sca/android-trivy.json "$APK_PATH"
      # ---------------------
      # Upload SCA Reports
      # ---------------------
      - name: Upload SCA Reports
        uses: actions/upload-artifact@v4
        with:
          name: sca-trivy-reports
          path: artifacts/sca/
