name: "SCA - Dependency Vulnerability Scan"

on:
  push:
    branches: [main]

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact folder
        run: mkdir -p artifacts/sca

      ##################################
      # React (Node.js) - Snyk SCA
      ##################################
      - name: Install Node.js dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Scan (React - Node.js)
        working-directory: ./frontend
        run: snyk test --file=package.json --json-file-output=../../artifacts/sca/snyk-node-report.json || true

      - name: Upload Snyk Node Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-node-report
          path: artifacts/sca/snyk-node-report.json

      ##################################
      # Java (Spring Boot) - Snyk SCA
      ##################################
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Snyk Scan (Java Maven - Spring Boot)
        working-directory: ./backend
        run: snyk test --file=pom.xml --json-file-output=../artifacts/sca/snyk-java-report.json || true

      - name: Upload Snyk Java Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-java-report
          path: artifacts/sca/snyk-java-report.json

      ##################################
      # Python (ML) - pip-audit SCA
      ##################################
      - name: Install PyTorch
        working-directory: ./ml
        run: |
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Install Python dependencies
        working-directory: ./ml
        run: pip install -r requirements.txt || true

      - name: Python Dependency Audit (pip-audit)
        working-directory: ./ml
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt -f json -o ../artifacts/sca/pip-audit-report.json || true

      - name: Upload pip-audit Report
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: artifacts/sca/pip-audit-report.json
